version: '3'

services:
  mysqlnacos:
    image: mysql:8.0.30
    container_name: mysq-nacos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yqKlmgs1cl
      MYSQL_DATABASE: nacos
      MYSQL_USER: nacos
      MYSQL_PASSWORD: liubei@2021
    ports:
      - 3306:3306
    volumes:
#      - ./mysql8/data/:/var/lib/mysql/
#      - ./mysql8/conf:/etc/mysql/conf.d
      -  ./mysql8/init/:/docker-entrypoint-initdb.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
  nacos:
    image: nacos/nacos-server
    container_name: nacos
    restart: always
    depends_on:
      - mysqlnacos
    environment:
      NACOS_AUTH_ENABLE: "false"
      SPRING_DATASOURCE_PLATFORM: mysql
      MODE: standalone
      NACOS_REPLICAS: 1
      MYSQL_SERVICE_HOST: mysqlnacos
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: liubei@2021
      NACOS_APPLICATION_PORT: 8848
      NACOS_SERVER_PORT: 8848
      PREFER_HOST_MODE: hostname
    volumes:
      - ./nacos/standalone-logs:/home/nacos/logs
      - ./nacos/plugins:/home/nacos/plugins
      - ./nacos/conf:/home/nacos/conf
      - ./nacos/data:/home/nacos/data
    ports:
      - "8848:8848"
  redis:
    image: redis:4.0.1
    container_name: redis-label
    volumes:
      - ./redis/datadir:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command: redis-server --requirepass 123456
    #   #  两个写入操作 只是为了解决启动后警告 可以去掉
    #    /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
    #    && echo never > /sys/kernel/mm/transparent_hugepage/enabled
    #    && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      # 使用宿主机的端口映射到容器的端口
      # 宿主机：容器
      - 6379:6379

